import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { Providers } from "./providers";
import MenuMain from "@/components/menu";
import clsx from "clsx";
import axios from "axios";
import { Footer } from "@/components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="light">
			<body className={clsx("", inter.className)}>
				<Header />
				<MenuMain />
				<Providers>{children}</Providers>
				<Footer />
			</body>
		</html>
	);
}
